---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AccessorMethodName:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
